"""
test_realms.py — Integration tests for Realm management.

Endpoints under test (Project Admin only):
  GET    /api/realms
  POST   /api/realms
  GET    /api/realms/:realmId
  PATCH  /api/realms/:realmId
  DELETE /api/realms/:realmId
  POST   /api/realms/:realmId/assign-senior
"""

from __future__ import annotations

import uuid

import pytest
import requests

from conftest import API, SEEDED_REALM_ID

pytestmark = pytest.mark.realms

# ─── helpers ─────────────────────────────────────────────────────────────────

def _unique_code() -> str:
    return f"TST-{uuid.uuid4().hex[:4].upper()}"


def _realm_payload(code: str | None = None) -> dict:
    code = code or _unique_code()
    return {
        "name": f"Test Realm {code}",
        "code": code,
        "description": "Auto-generated by test suite.",
        "semesterStart": "2026-01-01",
        "semesterEnd": "2026-06-30",
        "seniorAdmin": {
            "username": f"sr_{uuid.uuid4().hex[:6]}",
            "password": "Senior@5678",
            "displayName": "Test Senior",
        },
    }


# ─── List realms ──────────────────────────────────────────────────────────────

class TestListRealms:
    """GET /api/realms"""

    def test_project_admin_can_list_realms(self, admin_session: requests.Session) -> None:
        resp = admin_session.get(f"{API}/realms", timeout=10)
        assert resp.status_code == 200
        body = resp.json()
        assert body["success"] is True
        assert isinstance(body["data"], list)
        assert len(body["data"]) >= 1

    def test_senior_admin_cannot_list_realms(self, senior_session: requests.Session) -> None:
        """Non-project-admin users must receive 403."""
        resp = senior_session.get(f"{API}/realms", timeout=10)
        assert resp.status_code == 403

    def test_student_cannot_list_realms(self, student_session: requests.Session) -> None:
        resp = student_session.get(f"{API}/realms", timeout=10)
        assert resp.status_code == 403

    def test_unauthenticated_cannot_list_realms(self) -> None:
        resp = requests.get(f"{API}/realms", timeout=10)
        assert resp.status_code == 401


# ─── Get single realm ─────────────────────────────────────────────────────────

class TestGetRealm:
    """GET /api/realms/:realmId"""

    def test_project_admin_can_get_realm(self, admin_session: requests.Session) -> None:
        resp = admin_session.get(f"{API}/realms/{SEEDED_REALM_ID}", timeout=10)
        assert resp.status_code == 200
        body = resp.json()
        assert body["success"] is True
        assert body["data"]["id"] == SEEDED_REALM_ID

    def test_get_nonexistent_realm_returns_404(self, admin_session: requests.Session) -> None:
        fake_id = str(uuid.uuid4())
        resp = admin_session.get(f"{API}/realms/{fake_id}", timeout=10)
        assert resp.status_code == 404


# ─── Create realm ─────────────────────────────────────────────────────────────

class TestCreateRealm:
    """POST /api/realms"""

    def test_project_admin_can_create_realm(self, admin_session: requests.Session) -> None:
        payload = _realm_payload()
        resp = admin_session.post(f"{API}/realms", json=payload, timeout=15)
        assert resp.status_code == 201
        body = resp.json()
        assert body["success"] is True
        assert body["data"]["realm"]["code"] == payload["code"].upper()
        assert "id" in body["data"]["realm"]

    def test_create_realm_returns_senior_admin_user(self, admin_session: requests.Session) -> None:
        """Realm creation should auto-generate a senior admin user."""
        payload = _realm_payload()
        resp = admin_session.post(f"{API}/realms", json=payload, timeout=15)
        assert resp.status_code == 201
        body = resp.json()
        assert "seniorAdmin" in body["data"]
        assert body["data"]["seniorAdmin"]["role"] == "senior_admin"

    def test_create_realm_with_duplicate_code_returns_409(
        self, admin_session: requests.Session
    ) -> None:
        """Re-using an existing realm code must return 409."""
        payload = _realm_payload()
        # First creation succeeds
        r1 = admin_session.post(f"{API}/realms", json=payload, timeout=15)
        assert r1.status_code == 201
        # Second with same code fails
        payload2 = _realm_payload(code=payload["code"])
        payload2["seniorAdmin"]["username"] = f"sr_{uuid.uuid4().hex[:6]}"
        r2 = admin_session.post(f"{API}/realms", json=payload2, timeout=15)
        assert r2.status_code == 409

    def test_create_realm_missing_required_fields_returns_400(
        self, admin_session: requests.Session
    ) -> None:
        """Missing 'name' must return 400 with validation errors."""
        payload = _realm_payload()
        del payload["name"]
        resp = admin_session.post(f"{API}/realms", json=payload, timeout=15)
        assert resp.status_code == 400
        body = resp.json()
        assert body["success"] is False

    def test_senior_admin_cannot_create_realm(self, senior_session: requests.Session) -> None:
        payload = _realm_payload()
        resp = senior_session.post(f"{API}/realms", json=payload, timeout=15)
        assert resp.status_code == 403


# ─── Update realm ─────────────────────────────────────────────────────────────

class TestUpdateRealm:
    """PATCH /api/realms/:realmId"""

    def test_project_admin_can_update_realm_name(
        self, admin_session: requests.Session
    ) -> None:
        resp = admin_session.patch(
            f"{API}/realms/{SEEDED_REALM_ID}",
            json={"description": "Updated by test suite."},
            timeout=10,
        )
        assert resp.status_code == 200
        body = resp.json()
        assert body["success"] is True

    def test_senior_admin_cannot_update_realm(self, senior_session: requests.Session) -> None:
        resp = senior_session.patch(
            f"{API}/realms/{SEEDED_REALM_ID}",
            json={"description": "Should be denied."},
            timeout=10,
        )
        assert resp.status_code == 403


# ─── Archive realm ────────────────────────────────────────────────────────────

class TestArchiveRealm:
    """DELETE /api/realms/:realmId"""

    def test_project_admin_can_archive_a_fresh_realm(
        self, admin_session: requests.Session
    ) -> None:
        """Create a throwaway realm and then archive it."""
        payload = _realm_payload()
        create_resp = admin_session.post(f"{API}/realms", json=payload, timeout=15)
        assert create_resp.status_code == 201
        new_realm_id = create_resp.json()["data"]["realm"]["id"]

        delete_resp = admin_session.delete(
            f"{API}/realms/{new_realm_id}", timeout=10
        )
        assert delete_resp.status_code in (200, 204)

    def test_student_cannot_archive_realm(self, student_session: requests.Session) -> None:
        resp = student_session.delete(f"{API}/realms/{SEEDED_REALM_ID}", timeout=10)
        assert resp.status_code in (403, 401)
